enum ActionTypes {
  LUU_THOI_GIAN,
  TAI_DANH_SACH_GSHT_BAT_DAU,
  TAI_DANH_SACH_GSHT_XONG,
  TAI_DANH_SACH_GSHT_LOI,
  TAI_XONG_MAP_VIEW,
  LOADING_READY,
  LOADING_FINISH
}
export default ActionTypes;
